# NoobzVpn-Server Configuration File
# (c) Noobz-ID Software

[tcp_plain]
listen_ports = [8880]

[tcp_ssl]
listen_ports = [9443]
tls_version = "AUTO"
key_pem = "/etc/xray/xray.key"
cert_pem = "/etc/xray/xray.crt"

[client]
ip_version = "AUTO"
tcp_initial_timeout = 30
resolv_conf = "/etc/resolv.conf"
identifier = "noobz-id.github.io"
banner = "You are connected to noobzvpn-server"
tcp_http_response = "HTTP/1.1 101 Switching Protocols\r\nUpgrade: websocket\r\nConnection: Upgrade\r\n\r\n"

[remote]
tcp_connect_timeout = 30
tcp_idle_timeout = 1800
udp_connect_timeout = 30
udp_idle_timeout = 60
udp_dns_timeout = 10

[database]
database_monitor_timer = 30
device_timeout = 5

[runtime]
worker_threads = 0
